# Get the aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

export flight_ENV_root=$(cd $(dirname "${BASH_SOURCE[0]}")/.. && pwd)
. ${flight_ENV_root}/bin/flenv-fnwrapper.sh

set -e
flenv activate ${flight_ENV_subshell_env}
set +e
